% Script to generate test data and optimal partitions to be
% compared to provably optimal solutions generated by PDQ

min_mu = 0.5;
max_mu = 6;

min_d = 1/12;
max_d = 1;

min_N = 5;
max_N = 40;

NUM_TESTS = 1000;

type = [1, 1, 2, 2, 2];
numChains = length(find(type==1));
numCycles = length(find(type==2));

filenameroot = '2-3networks'

dlmwrite([filenameroot, 'config.txt'], NUM_TESTS);

for i = 1:NUM_TESTS
    
    mu = rand(1,length(type))*(max_mu-min_mu) + min_mu;
    d = rand(1,numCycles*numChains)*(max_d-min_d) + min_d;
    N = randi(max_N-min_N) + min_N - 1;
    
    dlmwrite([filenameroot, 'config.txt'], [mu,d,N], '-append', ...
             'delimiter', '\t');
    
    for METHOD = [1, 2, 4]
        [u,w,q,x,flag] = optimalAssignment(mu,type,d,N,METHOD);
        [Nvec, p] = routing(type, mu, d, x, N, METHOD);
    
        dlmwrite([filenameroot, 'solution_', num2str(METHOD), '.txt'], ...
                 [Nvec, flag], '-append', 'delimiter', '\t');
    end
    
end


